/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckResult {
  'isAnonymous' : boolean,
  'adminCount' : bigint,
  'hasAdmin' : boolean,
}
export interface CustomServerConfig {
  'bandwidthMbps' : bigint,
  'durationMonths' : bigint,
  'storageGb' : bigint,
  'ramGb' : bigint,
  'location' : string,
  'cpuCores' : bigint,
}
export interface Invoice {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'user' : Principal,
  'orderId' : string,
  'currency' : string,
  'amount' : bigint,
}
export interface Order {
  'id' : string,
  'status' : string,
  'createdAt' : Time,
  'user' : Principal,
  'serverPlan' : ServerPlan,
  'currency' : string,
  'price' : bigint,
}
export interface ServerPlan {
  'id' : string,
  'cpu' : string,
  'ram' : string,
  'bandwidth' : string,
  'storage' : string,
  'name' : string,
  'createdAt' : Time,
  'available' : boolean,
  'currency' : string,
  'pricePerMonth' : bigint,
  'location' : string,
}
export interface ShoppingCart {
  'total' : bigint,
  'createdAt' : Time,
  'currency' : string,
  'items' : Array<ServerPlan>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdatePlanInput {
  'id' : string,
  'cpu' : string,
  'ram' : string,
  'bandwidth' : string,
  'storage' : string,
  'name' : string,
  'available' : boolean,
  'currency' : string,
  'pricePerMonth' : bigint,
  'location' : string,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomServerToCart' : ActorMethod<[CustomServerConfig], ShoppingCart>,
  'addServerPlan' : ActorMethod<
    [string, string, string, string, string, string, bigint, string, boolean],
    ServerPlan
  >,
  'addToCart' : ActorMethod<[string], ShoppingCart>,
  'allUsers' : ActorMethod<[], Array<UserProfile>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoAssignAdminOnLogin' : ActorMethod<[], boolean>,
  'checkAdminStatus' : ActorMethod<[], CheckResult>,
  'checkout' : ActorMethod<[string, string], string>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], ShoppingCart>,
  'getCurrentUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPaymentStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getPlanById' : ActorMethod<[string], ServerPlan>,
  'getServerPlans' : ActorMethod<[], Array<ServerPlan>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserById' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserInvoices' : ActorMethod<[Principal], Array<Invoice>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdmin' : ActorMethod<[], boolean>,
  'isAdminSetUp' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'promoteToAdmin' : ActorMethod<[], undefined>,
  'promoteToAdminIfNeeded' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string, string], UserProfile>,
  'removeFromCart' : ActorMethod<[string], ShoppingCart>,
  'removeServerPlan' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDefaultPlans' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateServerPlan' : ActorMethod<[UpdatePlanInput], ServerPlan>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];