/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomServerConfig = IDL.Record({
  'bandwidthMbps' : IDL.Nat,
  'durationMonths' : IDL.Nat,
  'storageGb' : IDL.Nat,
  'ramGb' : IDL.Nat,
  'location' : IDL.Text,
  'cpuCores' : IDL.Nat,
});
export const Time = IDL.Int;
export const ServerPlan = IDL.Record({
  'id' : IDL.Text,
  'cpu' : IDL.Text,
  'ram' : IDL.Text,
  'bandwidth' : IDL.Text,
  'storage' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'available' : IDL.Bool,
  'currency' : IDL.Text,
  'pricePerMonth' : IDL.Nat,
  'location' : IDL.Text,
});
export const ShoppingCart = IDL.Record({
  'total' : IDL.Nat,
  'createdAt' : Time,
  'currency' : IDL.Text,
  'items' : IDL.Vec(ServerPlan),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServerStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'decommissioned' : IDL.Null,
  'available' : IDL.Null,
});
export const AssignedTo = IDL.Variant({
  'plan' : IDL.Text,
  'user' : IDL.Principal,
});
export const DedicatedServer = IDL.Record({
  'id' : IDL.Text,
  'status' : ServerStatus,
  'assignedTo' : IDL.Opt(AssignedTo),
  'name' : IDL.Text,
  'createdAt' : Time,
  'storageGb' : IDL.Nat,
  'updatedAt' : Time,
  'ramGb' : IDL.Nat,
  'cpuCores' : IDL.Nat,
});
export const CheckResult = IDL.Record({
  'isAnonymous' : IDL.Bool,
  'adminCount' : IDL.Nat,
  'hasAdmin' : IDL.Bool,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'serverPlan' : ServerPlan,
  'currency' : IDL.Text,
  'price' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdatePlanInput = IDL.Record({
  'cpu' : IDL.Text,
  'ram' : IDL.Text,
  'bandwidth' : IDL.Text,
  'storage' : IDL.Text,
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'currency' : IDL.Text,
  'pricePerMonth' : IDL.Nat,
  'location' : IDL.Text,
});
export const InvitationStatus = IDL.Variant({
  'found' : IDL.Record({ 'sender' : IDL.Principal }),
  'expired' : IDL.Null,
  'used' : IDL.Null,
  'notFound' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomServerToCart' : IDL.Func([CustomServerConfig], [ShoppingCart], []),
  'addServerPlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [ServerPlan],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Text], [ShoppingCart], []),
  'allUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignServerToPlan' : IDL.Func([IDL.Text, IDL.Text], [DedicatedServer], []),
  'assignServerToUser' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [DedicatedServer],
      [],
    ),
  'autoAssignAdminOnLogin' : IDL.Func([], [IDL.Bool], []),
  'checkAdminStatus' : IDL.Func([], [CheckResult], ['query']),
  'checkout' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'clearCart' : IDL.Func([], [], []),
  'createAdminInvitation' : IDL.Func([], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDedicatedServer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [DedicatedServer],
      [],
    ),
  'deleteDedicatedServer' : IDL.Func([IDL.Text], [], []),
  'getActiveInvitations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal))],
      ['query'],
    ),
  'getAllDedicatedServers' : IDL.Func(
      [],
      [IDL.Vec(DedicatedServer)],
      ['query'],
    ),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [ShoppingCart], ['query']),
  'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDedicatedServer' : IDL.Func([IDL.Text], [DedicatedServer], ['query']),
  'getInvitationCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getPlanById' : IDL.Func([IDL.Text], [ServerPlan], ['query']),
  'getServerPlans' : IDL.Func([], [IDL.Vec(ServerPlan)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserById' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserInvoices' : IDL.Func([IDL.Principal], [IDL.Vec(Invoice)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isAdminSetUp' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInvitationCodeValid' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'promoteToAdminIfNeeded' : IDL.Func([], [], []),
  'redeemAdminInvitation' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'removeFromCart' : IDL.Func([IDL.Text], [ShoppingCart], []),
  'removeServerPlan' : IDL.Func([IDL.Text], [], []),
  'resetAdminState' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDefaultPlans' : IDL.Func([], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateServerPlan' : IDL.Func([IDL.Text, UpdatePlanInput], [ServerPlan], []),
  'verifyInvitationCode' : IDL.Func([IDL.Text], [InvitationStatus], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomServerConfig = IDL.Record({
    'bandwidthMbps' : IDL.Nat,
    'durationMonths' : IDL.Nat,
    'storageGb' : IDL.Nat,
    'ramGb' : IDL.Nat,
    'location' : IDL.Text,
    'cpuCores' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ServerPlan = IDL.Record({
    'id' : IDL.Text,
    'cpu' : IDL.Text,
    'ram' : IDL.Text,
    'bandwidth' : IDL.Text,
    'storage' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'available' : IDL.Bool,
    'currency' : IDL.Text,
    'pricePerMonth' : IDL.Nat,
    'location' : IDL.Text,
  });
  const ShoppingCart = IDL.Record({
    'total' : IDL.Nat,
    'createdAt' : Time,
    'currency' : IDL.Text,
    'items' : IDL.Vec(ServerPlan),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServerStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'decommissioned' : IDL.Null,
    'available' : IDL.Null,
  });
  const AssignedTo = IDL.Variant({ 'plan' : IDL.Text, 'user' : IDL.Principal });
  const DedicatedServer = IDL.Record({
    'id' : IDL.Text,
    'status' : ServerStatus,
    'assignedTo' : IDL.Opt(AssignedTo),
    'name' : IDL.Text,
    'createdAt' : Time,
    'storageGb' : IDL.Nat,
    'updatedAt' : Time,
    'ramGb' : IDL.Nat,
    'cpuCores' : IDL.Nat,
  });
  const CheckResult = IDL.Record({
    'isAnonymous' : IDL.Bool,
    'adminCount' : IDL.Nat,
    'hasAdmin' : IDL.Bool,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'serverPlan' : ServerPlan,
    'currency' : IDL.Text,
    'price' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdatePlanInput = IDL.Record({
    'cpu' : IDL.Text,
    'ram' : IDL.Text,
    'bandwidth' : IDL.Text,
    'storage' : IDL.Text,
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'currency' : IDL.Text,
    'pricePerMonth' : IDL.Nat,
    'location' : IDL.Text,
  });
  const InvitationStatus = IDL.Variant({
    'found' : IDL.Record({ 'sender' : IDL.Principal }),
    'expired' : IDL.Null,
    'used' : IDL.Null,
    'notFound' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomServerToCart' : IDL.Func(
        [CustomServerConfig],
        [ShoppingCart],
        [],
      ),
    'addServerPlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [ServerPlan],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Text], [ShoppingCart], []),
    'allUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignServerToPlan' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DedicatedServer],
        [],
      ),
    'assignServerToUser' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [DedicatedServer],
        [],
      ),
    'autoAssignAdminOnLogin' : IDL.Func([], [IDL.Bool], []),
    'checkAdminStatus' : IDL.Func([], [CheckResult], ['query']),
    'checkout' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'clearCart' : IDL.Func([], [], []),
    'createAdminInvitation' : IDL.Func([], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDedicatedServer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [DedicatedServer],
        [],
      ),
    'deleteDedicatedServer' : IDL.Func([IDL.Text], [], []),
    'getActiveInvitations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal))],
        ['query'],
      ),
    'getAllDedicatedServers' : IDL.Func(
        [],
        [IDL.Vec(DedicatedServer)],
        ['query'],
      ),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [ShoppingCart], ['query']),
    'getCurrentUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDedicatedServer' : IDL.Func([IDL.Text], [DedicatedServer], ['query']),
    'getInvitationCodes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getPlanById' : IDL.Func([IDL.Text], [ServerPlan], ['query']),
    'getServerPlans' : IDL.Func([], [IDL.Vec(ServerPlan)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserInvoices' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isAdminSetUp' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInvitationCodeValid' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'promoteToAdminIfNeeded' : IDL.Func([], [], []),
    'redeemAdminInvitation' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'removeFromCart' : IDL.Func([IDL.Text], [ShoppingCart], []),
    'removeServerPlan' : IDL.Func([IDL.Text], [], []),
    'resetAdminState' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDefaultPlans' : IDL.Func([], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateServerPlan' : IDL.Func(
        [IDL.Text, UpdatePlanInput],
        [ServerPlan],
        [],
      ),
    'verifyInvitationCode' : IDL.Func(
        [IDL.Text],
        [InvitationStatus],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };