/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShoppingCart {
    total: bigint;
    createdAt: Time;
    currency: string;
    items: Array<ServerPlan>;
}
export type AssignedTo = {
    __kind__: "plan";
    plan: string;
} | {
    __kind__: "user";
    user: Principal;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface DedicatedServer {
    id: string;
    status: ServerStatus;
    assignedTo?: AssignedTo;
    name: string;
    createdAt: Time;
    storageGb: bigint;
    updatedAt: Time;
    ramGb: bigint;
    cpuCores: bigint;
}
export interface Invoice {
    id: string;
    status: string;
    createdAt: Time;
    user: Principal;
    orderId: string;
    currency: string;
    amount: bigint;
}
export interface CustomServerConfig {
    bandwidthMbps: bigint;
    durationMonths: bigint;
    storageGb: bigint;
    ramGb: bigint;
    location: string;
    cpuCores: bigint;
}
export interface Order {
    id: string;
    status: string;
    createdAt: Time;
    user: Principal;
    serverPlan: ServerPlan;
    currency: string;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UpdatePlanInput {
    cpu: string;
    ram: string;
    bandwidth: string;
    storage: string;
    name: string;
    available: boolean;
    currency: string;
    pricePerMonth: bigint;
    location: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type InvitationStatus = {
    __kind__: "found";
    found: {
        sender: Principal;
    };
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "used";
    used: null;
} | {
    __kind__: "notFound";
    notFound: null;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ServerPlan {
    id: string;
    cpu: string;
    ram: string;
    bandwidth: string;
    storage: string;
    name: string;
    createdAt: Time;
    available: boolean;
    currency: string;
    pricePerMonth: bigint;
    location: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    principal: Principal;
    name: string;
    createdAt: Time;
    email: string;
}
export interface CheckResult {
    isAnonymous: boolean;
    adminCount: bigint;
    hasAdmin: boolean;
}
export enum ServerStatus {
    assigned = "assigned",
    decommissioned = "decommissioned",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomServerToCart(config: CustomServerConfig): Promise<ShoppingCart>;
    addServerPlan(name: string, cpu: string, ram: string, storage: string, bandwidth: string, location: string, pricePerMonth: bigint, currency: string, available: boolean): Promise<ServerPlan>;
    addToCart(planId: string): Promise<ShoppingCart>;
    allUsers(): Promise<Array<UserProfile>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignServerToPlan(serverId: string, planId: string): Promise<DedicatedServer>;
    assignServerToUser(serverId: string, user: Principal): Promise<DedicatedServer>;
    autoAssignAdminOnLogin(): Promise<boolean>;
    checkAdminStatus(): Promise<CheckResult>;
    checkout(successUrl: string, cancelUrl: string): Promise<string>;
    clearCart(): Promise<void>;
    createAdminInvitation(): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDedicatedServer(id: string, name: string, cpuCores: bigint, ramGb: bigint, storageGb: bigint): Promise<DedicatedServer>;
    deleteDedicatedServer(serverId: string): Promise<void>;
    getActiveInvitations(): Promise<Array<[string, Principal]>>;
    getAllDedicatedServers(): Promise<Array<DedicatedServer>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<ShoppingCart>;
    getCurrentUserProfile(): Promise<UserProfile | null>;
    getDedicatedServer(serverId: string): Promise<DedicatedServer>;
    getInvitationCodes(): Promise<Array<string>>;
    getPaymentStatus(sessionId: string): Promise<StripeSessionStatus>;
    getPlanById(planId: string): Promise<ServerPlan>;
    getServerPlans(): Promise<Array<ServerPlan>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserById(user: Principal): Promise<UserProfile | null>;
    getUserInvoices(user: Principal): Promise<Array<Invoice>>;
    getUserOrders(user: Principal): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasAdmin(): Promise<boolean>;
    isAdminSetUp(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isInvitationCodeValid(_code: string): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    promoteToAdminIfNeeded(): Promise<void>;
    redeemAdminInvitation(code: string): Promise<boolean>;
    registerUser(name: string, email: string): Promise<UserProfile>;
    removeFromCart(planId: string): Promise<ShoppingCart>;
    removeServerPlan(planId: string): Promise<void>;
    resetAdminState(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDefaultPlans(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateServerPlan(planId: string, update: UpdatePlanInput): Promise<ServerPlan>;
    verifyInvitationCode(code: string): Promise<InvitationStatus>;
}
import type { AssignedTo as _AssignedTo, DedicatedServer as _DedicatedServer, InvitationStatus as _InvitationStatus, ServerStatus as _ServerStatus, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomServerToCart(arg0: CustomServerConfig): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomServerToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomServerToCart(arg0);
            return result;
        }
    }
    async addServerPlan(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: boolean): Promise<ServerPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.addServerPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServerPlan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addToCart(arg0: string): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0);
            return result;
        }
    }
    async allUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.allUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.allUsers();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignServerToPlan(arg0: string, arg1: string): Promise<DedicatedServer> {
        if (this.processError) {
            try {
                const result = await this.actor.assignServerToPlan(arg0, arg1);
                return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignServerToPlan(arg0, arg1);
            return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignServerToUser(arg0: string, arg1: Principal): Promise<DedicatedServer> {
        if (this.processError) {
            try {
                const result = await this.actor.assignServerToUser(arg0, arg1);
                return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignServerToUser(arg0, arg1);
            return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async autoAssignAdminOnLogin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.autoAssignAdminOnLogin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoAssignAdminOnLogin();
            return result;
        }
    }
    async checkAdminStatus(): Promise<CheckResult> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAdminStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAdminStatus();
            return result;
        }
    }
    async checkout(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(arg0, arg1);
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createAdminInvitation(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createAdminInvitation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAdminInvitation();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDedicatedServer(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<DedicatedServer> {
        if (this.processError) {
            try {
                const result = await this.actor.createDedicatedServer(arg0, arg1, arg2, arg3, arg4);
                return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDedicatedServer(arg0, arg1, arg2, arg3, arg4);
            return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDedicatedServer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDedicatedServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDedicatedServer(arg0);
            return result;
        }
    }
    async getActiveInvitations(): Promise<Array<[string, Principal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveInvitations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveInvitations();
            return result;
        }
    }
    async getAllDedicatedServers(): Promise<Array<DedicatedServer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDedicatedServers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDedicatedServers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getCurrentUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDedicatedServer(arg0: string): Promise<DedicatedServer> {
        if (this.processError) {
            try {
                const result = await this.actor.getDedicatedServer(arg0);
                return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDedicatedServer(arg0);
            return from_candid_DedicatedServer_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvitationCodes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvitationCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvitationCodes();
            return result;
        }
    }
    async getPaymentStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentStatus(arg0);
                return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentStatus(arg0);
            return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlanById(arg0: string): Promise<ServerPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanById(arg0);
            return result;
        }
    }
    async getServerPlans(): Promise<Array<ServerPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerPlans();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserInvoices(arg0: Principal): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserInvoices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserInvoices(arg0);
            return result;
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAdmin();
            return result;
        }
    }
    async isAdminSetUp(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminSetUp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminSetUp();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isInvitationCodeValid(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInvitationCodeValid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInvitationCodeValid(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async promoteToAdminIfNeeded(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteToAdminIfNeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteToAdminIfNeeded();
            return result;
        }
    }
    async redeemAdminInvitation(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemAdminInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemAdminInvitation(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async removeFromCart(arg0: string): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeServerPlan(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeServerPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeServerPlan(arg0);
            return result;
        }
    }
    async resetAdminState(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdminState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdminState();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedDefaultPlans(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultPlans();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateServerPlan(arg0: string, arg1: UpdatePlanInput): Promise<ServerPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServerPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServerPlan(arg0, arg1);
            return result;
        }
    }
    async verifyInvitationCode(arg0: string): Promise<InvitationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyInvitationCode(arg0);
                return from_candid_InvitationStatus_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyInvitationCode(arg0);
            return from_candid_InvitationStatus_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssignedTo_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignedTo): AssignedTo {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DedicatedServer_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DedicatedServer): DedicatedServer {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_InvitationStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvitationStatus): InvitationStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ServerStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServerStatus): ServerStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssignedTo]): AssignedTo | null {
    return value.length === 0 ? null : from_candid_AssignedTo_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ServerStatus;
    assignedTo: [] | [_AssignedTo];
    name: string;
    createdAt: _Time;
    storageGb: bigint;
    updatedAt: _Time;
    ramGb: bigint;
    cpuCores: bigint;
}): {
    id: string;
    status: ServerStatus;
    assignedTo?: AssignedTo;
    name: string;
    createdAt: Time;
    storageGb: bigint;
    updatedAt: Time;
    ramGb: bigint;
    cpuCores: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ServerStatus_n5(_uploadFile, _downloadFile, value.status),
        assignedTo: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedTo)),
        name: value.name,
        createdAt: value.createdAt,
        storageGb: value.storageGb,
        updatedAt: value.updatedAt,
        ramGb: value.ramGb,
        cpuCores: value.cpuCores
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n16(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: {
        sender: Principal;
    };
} | {
    expired: null;
} | {
    used: null;
} | {
    notFound: null;
}): {
    __kind__: "found";
    found: {
        sender: Principal;
    };
} | {
    __kind__: "expired";
    expired: null;
} | {
    __kind__: "used";
    used: null;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "found" in value ? {
        __kind__: "found",
        found: value.found
    } : "expired" in value ? {
        __kind__: "expired",
        expired: value.expired
    } : "used" in value ? {
        __kind__: "used",
        used: value.used
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    decommissioned: null;
} | {
    available: null;
}): ServerStatus {
    return "assigned" in value ? ServerStatus.assigned : "decommissioned" in value ? ServerStatus.decommissioned : "available" in value ? ServerStatus.available : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    plan: string;
} | {
    user: Principal;
}): {
    __kind__: "plan";
    plan: string;
} | {
    __kind__: "user";
    user: Principal;
} {
    return "plan" in value ? {
        __kind__: "plan",
        plan: value.plan
    } : "user" in value ? {
        __kind__: "user",
        user: value.user
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DedicatedServer>): Array<DedicatedServer> {
    return value.map((x)=>from_candid_DedicatedServer_n3(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
